export {logout} from "./useLogout.jsx"
export {useLogin} from "./useLogin.jsx"
export {useRegister} from "./useRegister.jsx"
export {useUserDetails} from "./useUserDetails.jsx"
export {useGetHotelsByName} from "./useGetHotels.jsx"
export {useAcceptUser} from "./useAcceptUser.jsx"
export {useGetUsers} from "./useGetUsers.jsx"
export {useAddHotel} from "./useAddHotel.jsx"
export {useAddReservation} from "./useAddReservacion.jsx"

